### ISSUE TITLE
Login Failed: 'The words you typed didn't match the picture. Please try again.'

### ISSUE THREAD

**Issue by opplo** [sentanos/roblox-js#107]
When I use rbx.login(username, password) I am getting the following error and cannot log in. I believe this may be related to a Roblox image CAPTCHA. I can't find any information on this error anywhere.

```
Unhandled rejection Error: Login failed, known issues: ["The words you typed didn't match the picture. Please try again."]
    at C:\Users\user\node_modules\roblox-js\lib\user\login.js:64:13
    at tryCatcher (C:\Users\user\node_modules\roblox-js\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\user\node_modules\roblox-js\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\user\node_modules\roblox-js\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\user\node_modules\roblox-js\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\user\node_modules\roblox-js\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\user\node_modules\roblox-js\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\user\node_modules\roblox-js\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\user\node_modules\roblox-js\node_modules\bluebird\js\release\async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

**Comment by opplo** [comment]
Although this repo doesn't seem to be maintained anymore...

**Comment by EraGamer** [comment]
This is a result of the captcha. Use a jar/cookie to bypass this. 

And you're correct, roblox-js is no longer maintained.

**Comment by LingleDev** [comment]
@EraGamer how would I do that?

**Comment by fabuss254** [comment]
how do you log with a jar/cookie @EraGamer ?
