### ISSUE TITLE
error when hosting on Cloud9

### ISSUE THREAD

**Issue by Vritix** [sentanos/roblox-js#27]
When hosting on cloud9, starting the Discord bot and logging into the account this error occurs : (I believe it's a roblox-js error)

Unhandled rejection RequestError: Error: ETIMEDOUT
    at new RequestError (/home/ubuntu/workspace/node_modules/request-promise/lib/errors.js:14:15)
    at Request.RP$callback [as _callback] (/home/ubuntu/workspace/node_modules/request-promise/lib/rp.js:60:25)
    at self.callback (/home/ubuntu/workspace/node_modules/request/request.js:188:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Timeout._onTimeout (/home/ubuntu/workspace/node_modules/request/request.js:855:16)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

**Comment by sentanos** [comment]
Not sure if you figured it out or not but to clarify this is not a roblox-js error but happens because ROBLOX blocked all requests from cloud9 servers because too many people were using them to run bots.
