### ISSUE TITLE
Shout function

### ISSUE THREAD

**Issue by nishi7409** [sentanos/roblox-js#47]
Every time I run the code below, I receive a, "Maximum call stack size exceeded", message.

Code...
`  if (message.content.startsWith(prefix + "shout")) {
    let modRole = message.guild.roles.find("name", "admin");
    if (!message.member.roles.has(modRole.id)) {
      return message.author.send("You can't run the shout command!")
    }
    else{
      let args = message.content.split(" ").slice(1);
      rbx.shout(3413402, args[1], jar)
      message.channel.send("I've successfully shouted that message!")
    }
    let channel = bot.channels.get('344621842289524746')
    const embed = new Discord.RichEmbed()
    .setColor('0x32b55b')
    .addField('Action(s) Taken', "Shouted Message!")
    .addField('Administrator', `${message.author}`)
    .addField("User's Message", `${message.content}`)
    bot.channels.get(channel.id).sendEmbed(embed)
  }`

Error...
function arrayClone(arr, n) {
                   ^

RangeError: Maximum call stack size exceeded
    at arrayClone (events.js:514:20)
    at emitNone (events.js:108:21)
    at IncomingMessage.emit (events.js:207:7)
    at IncomingMessage.<anonymous> (/Users/OnlyJumpAdministrator/Desktop/SOVEREIGN/botstuff/node_modules/request/request.js:950:39)
    at emitNone (events.js:105:13)
    at IncomingMessage.emit (events.js:207:7)
    at IncomingMessage.<anonymous> (_http_client.js:370:11)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at IncomingMessage.<anonymous> (/Users/OnlyJumpAdministrator/Desktop/SOVEREIGN/botstuff/node_modules/request/request.js:950:39)
    at emitNone (events.js:105:13)
    at IncomingMessage.emit (events.js:207:7)
    at IncomingMessage.<anonymous> (_http_client.js:370:11)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at IncomingMessage.<anonymous> (/Users/OnlyJumpAdministrator/Desktop/SOVEREIGN/botstuff/node_modules/request/request.js:950:39)
    at emitNone (events.js:105:13)
    at IncomingMessage.emit (events.js:207:7)
    at IncomingMessage.<anonymous> (_http_client.js:370:11)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at IncomingMessage.<anonymous> (/Users/OnlyJumpAdministrator/Desktop/SOVEREIGN/botstuff/node_modules/request/request.js:950:39)

**Comment by sentanos** [comment]
Are you sure you are logged into `jar`? Where is the definition of `jar`?
If you logged in without passing the same `jar` file into `rbx.login` you shouldn't pass in anything for jar in other functions.

**Comment by sentanos** [comment]
Just show your login code with username and password removed.

**Comment by sentanos** [comment]
Also be sure the error is originating from roblox-js and is not due to something else or a server configuration error. I'm not sure why that error would appear from shout.

**Comment by nishi7409** [comment]
https://hastebin.com/iyifigijew.js

I believe, ROBLOX only allows you to shout multiple times after a couple minutes after each shout, correct me if I'm wrong.

**Comment by sentanos** [comment]
No, you can shout anytime. Your problem is something else. Although it wouldn't technically cause a problem, you don't have to be passing in jar anyways. You can just do `rbx.shout(group, message)` and it will shout using the global logged in user.

In order to isolate the problem try running `rbx.getCurrentUser().then(console.log)` once the login has completed and show the output.

**Comment by nishi7409** [comment]
![image](https://user-images.githubusercontent.com/20250366/29344034-3239871c-8203-11e7-9476-535915a0fa55.png)

**Comment by sentanos** [comment]
When you use `rbx.shout(314302, 'test')` after login (not prompted by the command) what is the output?

**Comment by nishi7409** [comment]
![image](https://user-images.githubusercontent.com/20250366/29344454-e9e9d69e-8205-11e7-8697-69b5c1ed5dd3.png)

This was the code...
https://hastebin.com/lupisobube.js

**Comment by sentanos** [comment]
Well... did it shout?

**Comment by nishi7409** [comment]
Yes, it shouted.
  

  
  

  
  
>

**Comment by sentanos** [comment]
Then it doesn't sound like a problem with the module. Either you are passing in incorrect arguments or it is something with the discord module errorring.

**Comment by nishi7409** [comment]
Ah, I see what I was doing wrong...

Thanks!
