### ISSUE TITLE
having issues with certificates o3o

### ISSUE THREAD

**Issue by xbaheeg** [sentanos/roblox-js#6]
so this is my current code
```
var rbx = require('roblox-js');
console.log('started');
var obj = rbx.getPlayers(2901888)
```

and it logged the following:

started
```
Http error: RequestError: Error: CERT_UNTRUSTED
    at new RequestError (/home/ubuntu/node_modules/request-promise/lib/errors.:14:15)
    at Request.RP$callback [as _callback] (/home/ubuntu/node_modules/request-pmise/lib/rp.js:60:25)
    at self.callback (/home/ubuntu/node_modules/request/request.js:187:22)
    at Request.EventEmitter.emit (events.js:95:17)
    at Request.onRequestError (/home/ubuntu/node_modules/request/request.js:818)
    at ClientRequest.EventEmitter.emit (events.js:95:17)
    at CleartextStream.socketErrorListener (http.js:1547:9)
    at CleartextStream.EventEmitter.emit (events.js:95:17)
    at SecurePair.<anonymous> (tls.js:1389:19)
    at SecurePair.EventEmitter.emit (events.js:92:17)
    at SecurePair.maybeInitFinished (tls.js:982:10)
    at CleartextStream.read [as _read] (tls.js:469:13)
    at CleartextStream.Readable.read (_stream_readable.js:320:10)
    at EncryptedStream.write [as _write] (tls.js:366:25)
    at doWrite (_stream_writable.js:223:10)
    at writeOrBuffer (_stream_writable.js:213:5)
Unhandled rejection SyntaxError: Unexpected token u
    at Object.parse (native)
    at /home/ubuntu/node_modules/roblox-js/lib/util/getRoles.js:16:20
    at tryCatcher (/home/ubuntu/node_modules/bluebird/js/release/util.js:16:23
    at Promise._settlePromiseFromHandler (/home/ubuntu/node_modules/bluebird/jrelease/promise.js:510:31)
    at Promise._settlePromise (/home/ubuntu/node_modules/bluebird/js/release/pmise.js:567:18)
    at Promise._settlePromise0 (/home/ubuntu/node_modules/bluebird/js/release/omise.js:612:10)
    at Promise._settlePromises (/home/ubuntu/node_modules/bluebird/js/release/omise.js:691:18)
    at Async._drainQueue (/home/ubuntu/node_modules/bluebird/js/release/async.:138:16)
    at Async._drainQueues (/home/ubuntu/node_modules/bluebird/js/release/asyncs:148:10)
    at Async.drainQueues (/home/ubuntu/node_modules/bluebird/js/release/async.:17:14)
    at process._tickCallback (node.js:415:13)

```

**Comment by sentanos** [comment]
This is not an issue with the module, this is a problem with your server setup: please fix the certificate problem there. Unfortunately you do need it to work because ROBLOX forces https.
