### ISSUE TITLE
Trying to use GroupPayout in the server.

### ISSUE THREAD

**Issue by SparkleOff** [sentanos/roblox-js#9]
Trying to do this:
http://pastebin.com/Bj4mEwrN

I get an internal server error and these are some errors i get:
A required argument is missing
    at Object.groupPayout (/home/susa/public_html/immigration/roblox-js-server/node_modules/roblo       x-js/lib/util/wrap.js:67:19)
    at /home/susa/public_html/immigration/roblox-js-server/server.js:344:7
    at Layer.handle [as handle_request] (/home/susa/public_html/immigration/roblox-js-server/node       _modules/express/lib/router/layer.js:95:5)
    at next (/home/susa/public_html/immigration/roblox-js-server/node_modules/express/lib/router/       route.js:131:13)
    at authenticate (/home/susa/public_html/immigration/roblox-js-server/server.js:129:5)

**Comment by sentanos** [comment]
The argument "user" should be changed to "member" per the API.

**Comment by SparkleOff** [comment]
Woops simple little mistake, thank you so much it works.
